"""Simulation generators for Lab 1 experiments."""

from ugradio_lab1.sim.mixers import (
    DSBSpurSimulation,
    pick_top_spectral_lines,
    simulate_dsb_output,
    simulate_dsb_spur_survey,
    simulate_nonlinear_mixer_output,
    simulate_r820t_vs_external,
    simulate_reverted_dsb_iq,
    simulate_ssb_iq,
)
from ugradio_lab1.sim.noise import (
    ACFConsistencySimulation,
    RadiometerSimulation,
    bandlimit_noise,
    generate_gaussian_noise,
    generate_gaussian_noise_blocks,
    simulate_acf_consistency,
    simulate_noise_capture,
    simulate_radiometer_experiment,
)
from ugradio_lab1.sim.nyquist import (
    AliasSweepSimulation,
    LeakageSimulation,
    ResolutionSweepSimulation,
    estimate_peak_frequency,
    generate_multi_tone,
    generate_tone,
    ideal_bandpass_gain,
    sample_times,
    simulate_alias_sweep,
    simulate_bandpass_sweep,
    simulate_leakage_experiment,
    simulate_multi_window_spectrum,
    simulate_resolution_sweep,
)

__all__ = [
    "ACFConsistencySimulation",
    "AliasSweepSimulation",
    "DSBSpurSimulation",
    "LeakageSimulation",
    "RadiometerSimulation",
    "ResolutionSweepSimulation",
    "bandlimit_noise",
    "estimate_peak_frequency",
    "generate_gaussian_noise",
    "generate_gaussian_noise_blocks",
    "generate_multi_tone",
    "generate_tone",
    "ideal_bandpass_gain",
    "pick_top_spectral_lines",
    "sample_times",
    "simulate_acf_consistency",
    "simulate_alias_sweep",
    "simulate_bandpass_sweep",
    "simulate_dsb_output",
    "simulate_dsb_spur_survey",
    "simulate_leakage_experiment",
    "simulate_multi_window_spectrum",
    "simulate_noise_capture",
    "simulate_nonlinear_mixer_output",
    "simulate_r820t_vs_external",
    "simulate_radiometer_experiment",
    "simulate_resolution_sweep",
    "simulate_reverted_dsb_iq",
    "simulate_ssb_iq",
]
